import { defineStore } from 'pinia';

export const useMenuStore = defineStore({
    id: 'menu',
    state: () => ({
        activeTopMenu: localStorage.getItem('activeTopMenu') || '1',
        activeSidebarMenu: localStorage.getItem('activeSidebarMenu') || '1',
        menuItems: [
            // 武器类 index 全部为 1
            { type: '1', index: '1', name: '破损的短剑', path: '/weapon/WornShortsword', url: '/images/weapons/part-Slice67.png' },
            { type: '1', index: '2', name: '镶钉手套', path: '/weapon/StuddedGloves', url: '/images/weapons/part-Slice68.png' },
            { type: '1', index: '3', name: '匕首', path: '/weapon/Dagger', url: '/images/weapons/part-Slice70.png' },
            { type: '1', index: '4', name: '魔杖', path: '/weapon/MageStaff', url: '/images/weapons/part-Slice71.png' },
            { type: '1', index: '5', name: '刺剑', path: '/weapon/RapierView', url: '/images/weapons/part-Slice69.png' },
            { type: '1', index: '6', name: '短剑', path: '/weapon/ShortSword', url: '/images/weapons/part-Slice72.png' },
            { type: '1', index: '7', name: '手斧', path: '/weapon/HandAxe', url: '/images/weapons/part-Slice73.png' },
            { type: '1', index: '8', name: '长矛', path: '/weapon/SpearView', url: '/images/weapons/part-Slice74.png' },
            { type: '1', index: '9', name: '铁头棍', path: '/weapon/QuarterstaffView', url: '/images/weapons/part-Slice75.png' },
            { type: '1', index: '10', name: '长匕首', path: '/weapon/DirkView', url: '/images/weapons/part-Slice76.png' },
            { type: '1', index: '11', name: '短柄镰', path: '/weapon/SickleView', url: '/images/weapons/part-Slice77.png' },
            { type: '1', index: '12', name: '单手剑', path: '/weapon/SwordView', url: '/images/weapons/part-Slice78.png' },
            { type: '1', index: '13', name: '硬头锤', path: '/weapon/MaceView', url: '/images/weapons/part-Slice79.png' },
            { type: '1', index: '14', name: '弯刀', path: '/weapon/ScimitarView', url: '/images/weapons/part-Slice80.png' },
            { type: '1', index: '15', name: '圆盾', path: '/weapon/RoundShield', url: '/images/weapons/part-Slice81.png' },
            { type: '1', index: '16', name: '双钗', path: '/weapon/SaiView', url: '/images/weapons/part-Slice82.png' },
            { type: '1', index: '17', name: '长鞭', path: '/weapon/WhipView', url: '/images/weapons/part-Slice83.png' },
            { type: '1', index: '18', name: '武士刀', path: '/weapon/KatanaView', url: '/images/weapons/part-Slice90.png' },
            { type: '1', index: '19', name: '长剑', path: '/weapon/LongSword', url: '/images/weapons/part-Slice84.png' },
            { type: '1', index: '20', name: '战斧', path: '/weapon/BattleAxe', url: '/images/weapons/part-Slice85.png' },
            { type: '1', index: '21', name: '链枷', path: '/weapon/FlailView', url: '/images/weapons/part-Slice86.png' },
            { type: '1', index: '22', name: '符文之刃', path: '/weapon/RunicBlade', url: '/images/weapons/part-Slice87.png' },
            { type: '1', index: '23', name: '暗杀之刃', path: '/weapon/AssassinsBlade', url: '/images/weapons/part-Slice88.png' },
            { type: '1', index: '24', name: '十字弩', path: '/weapon/CrossbowView', url: '/images/weapons/part-Slice89.png' },
            { type: '1', index: '25', name: '战镰', path: '/weapon/WarScythe', url: '/images/weapons/part-Slice97.png' },
            { type: '1', index: '26', name: '巨剑', path: '/weapon/GreatSword', url: '/images/weapons/part-Slice91.png' },
            { type: '1', index: '27', name: '战锤', path: '/weapon/WarHammer', url: '/images/weapons/part-Slice92.png' },
            { type: '1', index: '28', name: '关刀', path: '/weapon/GlaiveView', url: '/images/weapons/part-Slice93.png' },
            { type: '1', index: '29', name: '巨斧', path: '/weapon/GreatAxe', url: '/images/weapons/part-Slice94.png' },
            { type: '1', index: '30', name: '巨型方盾', path: '/weapon/GreatShield', url: '/images/weapons/part-Slice95.png' },
            { type: '1', index: '31', name: '魔岩拳套', path: '/weapon/StoneGauntlet', url: '/images/weapons/part-Slice96.png' },
            { type: '1', index: '32', name: '决斗家武技', path: '/weapon/DuelistAbility', url: '/images/weapons/part-weapon.png' },
            { type: '1', index: '33', name: '常见附魔', path: '/weapon/CommonWeaponench', url: '/images/weapons/part-Slice229.png' },
            { type: '1', index: '34', name: '稀有附魔', path: '/weapon/ScarceWeaponench', url: '/images/weapons/part-Slice229.png' },
            { type: '1', index: '35', name: '罕见附魔', path: '/weapon/RareWeaponench', url: '/images/weapons/part-Slice229.png' },
            { type: '1', index: '36', name: '诅咒附魔', path: '/weapon/CurseWeaponench', url: '/images/weapons/part-Slice288.png' },
            { type: '1', index: '37', name: '飞镖', path: '/weapon/MissileDart', url: '/images/weapons/part-Slice114.png' },
            { type: '1', index: '38', name: '涂药飞镖', path: '/weapon/MissileDarttipped', url: '/images/weapons/part-Slice123.png' },
            { type: '1', index: '39', name: '石子', path: '/weapon/MissileStone', url: '/images/weapons/part-Slice101.png' },
            { type: '1', index: '40', name: '飞刀', path: '/weapon/MissileKnife', url: '/images/weapons/part-Slice100.png' },
            { type: '1', index: '41', name: '捕鱼矛', path: '/weapon/MissileFishing', url: '/images/weapons/part-Slice102.png' },
            { type: '1', index: '42', name: '手里剑', path: '/weapon/MissileShuriken', url: '/images/weapons/part-Slice103.png' },
            { type: '1', index: '43', name: '飞槌', path: '/weapon/MissileClub', url: '/images/weapons/part-Slice104.png' },
            { type: '1', index: '44', name: '投矛', path: '/weapon/MissileSpear', url: '/images/weapons/part-Slice105.png' },
            { type: '1', index: '45', name: '苦无', path: '/weapon/MissileKunai', url: '/images/weapons/part-Slice107.png' },
            { type: '1', index: '46', name: '流星锤', path: '/weapon/MissileBolas', url: '/images/weapons/part-Slice106.png' },
            { type: '1', index: '47', name: '标枪', path: '/weapon/MissileJavelin', url: '/images/weapons/part-Slice108.png' },
            { type: '1', index: '48', name: '重型回旋镖', path: '/weapon/MissileBoomerang', url: '/images/weapons/part-Slice110.png' },
            { type: '1', index: '49', name: '飞斧', path: '/weapon/MissileAxe', url: '/images/weapons/part-Slice109.png' },
            { type: '1', index: '50', name: '投掷锤', path: '/weapon/MissileHammer', url: '/images/weapons/part-Slice112.png' },
            { type: '1', index: '51', name: '三叉戟', path: '/weapon/MissileTrident', url: '/images/weapons/part-Slice111.png' },
            { type: '1', index: '52', name: '震爆方石', path: '/weapon/MissileCube', url: '/images/weapons/part-Slice113.png' },
            { type: '1', index: '53', name: '灵能短弓', path: '/weapon/MissileSpiritbow', url: '/images/weapons/part-Slice98.png' },

            // 护甲类 index 全部为 2
            { type: '2', index: '1', name: '布甲', path: '/armor/ClothView', url: '/images/armors/part-Slice127.png' },
            { type: '2', index: '2', name: '皮甲', path: '/armor/LeatherView', url: '/images/armors/part-Slice128.png' },
            { type: '2', index: '3', name: '链甲', path: '/armor/MailView', url: '/images/armors/part-Slice129.png' },
            { type: '2', index: '4', name: '鳞甲', path: '/armor/ScaleView', url: '/images/armors/part-Slice130.png' },
            { type: '2', index: '5', name: '板甲', path: '/armor/PlateView', url: '/images/armors/part-Slice131.png' },
            { type: '2', index: '6', name: '英雄护甲', path: '/armor/EpicView', url: '/images/armors/part-Slice132.png' },
            { type: '2', index: '7', name: '常见刻印', path: '/armor/ArmorCommonglyph', url: '/images/armors/part-Slice34.png' },
            { type: '2', index: '8', name: '稀有刻印', path: '/armor/ArmorScarceglyph', url: '/images/armors/part-Slice34.png' },
            { type: '2', index: '9', name: '罕见刻印', path: '/armor/ArmorRareglyph', url: '/images/armors/part-Slice34.png' },
            { type: '2', index: '10', name: '诅咒刻印', path: '/armor/ArmorCurseglyph', url: '/images/armors/part-Slice288.png' },

            //法杖类
            { type: '3', index: '1', name: '冲击波法杖', path: '/wand/WandBlastwave', url: '/images/wand/part-Slice145.png' },
            { type: '3', index: '2', name: '酸蚀法杖', path: '/wand/WandCorrosion', url: '/images/wand/part-Slice143.png' },
            { type: '3', index: '3', name: '腐化法杖', path: '/wand/WandCorruption', url: '/images/wand/part-Slice146.png' },
            { type: '3', index: '4', name: '解离法杖', path: '/wand/WandBeam', url: '/images/wand/part-Slice141.png' },
            { type: '3', index: '5', name: '焰浪法杖', path: '/wand/WandFireblast', url: '/images/wand/part-Slice138.png' },
            { type: '3', index: '6', name: '冰霜法杖', path: '/wand/WandForst', url: '/images/wand/part-Slice139.png' },
            { type: '3', index: '7', name: '雷霆法杖', path: '/wand/WandLightning', url: '/images/wand/part-Slice140.png' },
            { type: '3', index: '8', name: '灵壤法杖', path: '/wand/WandSoil', url: '/images/wand/part-Slice144.png' },
            { type: '3', index: '9', name: '魔弹法杖', path: '/wand/WandMagicmissile', url: '/images/wand/part-Slice137.png' },
            { type: '3', index: '10', name: '棱光法杖', path: '/wand/WandLight', url: '/images/wand/part-Slice142.png' },
            { type: '3', index: '11', name: '再生法杖', path: '/wand/WandGrass', url: '/images/wand/part-Slice148.png' },
            { type: '3', index: '12', name: '注魂法杖', path: '/wand/WandTransfusion', url: '/images/wand/part-Slice149.png' },
            { type: '3', index: '13', name: '哨卫法杖', path: '/wand/WandWarding', url: '/images/wand/part-Slice147.png' },

            //戒指类
            { type: '4', index: '1', name: '精准之戒', path: '/ring/RingAccuracy', url: '/images/ring/part-Slice160.png' },
            { type: '4', index: '2', name: '元素之戒', path: '/ring/RingElement', url: '/images/ring/part-Slice160.png' },
            { type: '4', index: '3', name: '奥术之戒', path: '/ring/RingArcana', url: '/images/ring/part-Slice160.png' },
            { type: '4', index: '4', name: '能量戒指', path: '/ring/RingEnergy', url: '/images/ring/part-Slice161.png' },
            { type: '4', index: '5', name: '闪避之戒', path: '/ring/RingEvasion', url: '/images/ring/part-Slice161.png' },
            { type: '4', index: '6', name: '武力之戒', path: '/ring/RingForce', url: '/images/ring/part-Slice161.png' },
            { type: '4', index: '7', name: '狂怒之戒', path: '/ring/RingFuror', url: '/images/ring/part-Slice153.png' },
            { type: '4', index: '8', name: '疾速之戒', path: '/ring/RingHaste', url: '/images/ring/part-Slice153.png' },
            { type: '4', index: '9', name: '根骨之戒', path: '/ring/RingMight', url: '/images/ring/part-Slice153.png' },
            { type: '4', index: '10', name: '神射之戒', path: '/ring/RingShoot', url: '/images/ring/part-Slice159.png' },
            { type: '4', index: '11', name: '韧性之戒', path: '/ring/RingTenacity', url: '/images/ring/part-Slice159.png' },
            { type: '4', index: '12', name: '财富之戒', path: '/ring/RingWealth', url: '/images/ring/part-Slice159.png' },

            //神器类
            { type: '5', index: '1', name: '炼金工具箱', path: '/artifact/ToolkitView', url: '/images/artifact/part-Slice167.png' },
            { type: '5', index: '2', name: '蓄血圣杯', path: '/artifact/ChaliceView', url: '/images/artifact/part-Slice175.png' },
            { type: '5', index: '3', name: '暗影斗篷', path: '/artifact/CloakView', url: '/images/artifact/part-Slice162.png' },
            { type: '5', index: '4', name: '干枯玫瑰', path: '/artifact/RoseView', url: '/images/artifact/part-Slice182.png' },
            { type: '5', index: '5', name: '虚空锁链', path: '/artifact/ChainView', url: '/images/artifact/part-Slice170.png' },
            { type: '5', index: '6', name: '丰饶之角', path: '/artifact/HornView', url: '/images/artifact/part-Slice171.png' },
            { type: '5', index: '7', name: '自然之履', path: '/artifact/SandalView', url: '/images/artifact/part-Slice178.png' },
            { type: '5', index: '8', name: '先见护符', path: '/artifact/TalismanView', url: '/images/artifact/part-Slice165.png' },
            { type: '5', index: '9', name: '神偷袖章', path: '/artifact/ArmbandView', url: '/images/artifact/part-Slice163.png' },
            { type: '5', index: '10', name: '时光沙漏', path: '/artifact/HourglassView', url: '/images/artifact/part-Slice166.png' },
            { type: '5', index: '11', name: '无序魔典', path: '/artifact/BookView', url: '/images/artifact/part-Slice168.png' },

            //炼金类
            { type: '6', index: '1', name: '炸弹', path: '/alchemy/BombView', url: '/images/alchemy/part-Slice55.png' },
            { type: '6', index: '2', name: '寒霜炸弹', path: '/alchemy/BombFrost', url: '/images/alchemy/part-Slice58.png' },
            { type: '6', index: '3', name: '燃烧弾', path: '/alchemy/BombFlame', url: '/images/alchemy/part-Slice57.png' },
            { type: '6', index: '4', name: '绵绵炸弹', path: '/alchemy/BombWool', url: '/images/alchemy/part-Slice63.png' },
            { type: '6', index: '5', name: '鞭炮', path: '/alchemy/BombNoise', url: '/images/alchemy/part-Slice64.png' },
            { type: '6', index: '6', name: '闪光弹', path: '/alchemy/BombFlash', url: '/images/alchemy/part-Slice60.png' },
            { type: '6', index: '7', name: '电击炸弹', path: '/alchemy/BombShocking', url: '/images/alchemy/part-Slice61.png' },
            { type: '6', index: '8', name: '再生炸弹', path: '/alchemy/BombRegrowth', url: '/images/alchemy/part-Slice59.png' },
            { type: '6', index: '9', name: '神圣炸弹', path: '/alchemy/BombHoly', url: '/images/alchemy/part-Slice62.png' },
            { type: '6', index: '10', name: '奥术炸弹', path: '/alchemy/BombArcane', url: '/images/alchemy/part-Slice65.png' },
            { type: '6', index: '11', name: '破片爆弹', path: '/alchemy/BombShrapnel', url: '/images/alchemy/part-Slice66.png' },
            { type: '6', index: '12', name: '备用口粮', path: '/alchemy/FoodRation', url: '/images/alchemy/part-Slice300.png' },
            { type: '6', index: '13', name: '肉', path: '/alchemy/FoodFrozen', url: '/images/alchemy/part-Slice299.png' },
            { type: '6', index: '14', name: '全肉大饼', path: '/alchemy/FoodPie', url: '/images/alchemy/part-Slice302.png' },
            { type: '6', index: '15', name: '肉馅饼', path: '/alchemy/FoodPasty', url: '/images/alchemy/part-Slice301.png' },
            { type: '6', index: '16', name: '无味果', path: '/alchemy/FoodFruit', url: '/images/alchemy/part-Slice303.png' },
            { type: '6', index: '17', name: '无味果块', path: '/alchemy/FoodChunk', url: '/images/alchemy/part-Slice304.png' },
            { type: '6', index: '18', name: '地牢浆果', path: '/alchemy/FoodBerry', url: '/images/alchemy/part-Slice305.png' },
            { type: '6', index: '19', name: '幻影鱼肉', path: '/alchemy/PhantomMeat', url: '/images/alchemy/part-Slice306.png' },
            { type: '6', index: '20', name: '经验药剂', path: '/alchemy/PotionExp', url: '/images/alchemy/part-Slice239.png' },
            { type: '6', index: '21', name: '冰霜药剂', path: '/alchemy/PotionFrost', url: '/images/alchemy/part-Slice239.png' },
            { type: '6', index: '22', name: '极速药剂', path: '/alchemy/PotionHaste', url: '/images/alchemy/part-Slice239.png' },
            { type: '6', index: '23', name: '治疗药剂', path: '/alchemy/PotionHealing', url: '/images/alchemy/part-Slice238.png' },
            { type: '6', index: '24', name: '隐形药剂', path: '/alchemy/PotionInv', url: '/images/alchemy/part-Slice238.png' },
            { type: '6', index: '25', name: '浮空药剂', path: '/alchemy/PotionFly', url: '/images/alchemy/part-Slice238.png' },
            { type: '6', index: '26', name: '液火药剂', path: '/alchemy/PotionFire', url: '/images/alchemy/part-Slice236.png' },
            { type: '6', index: '27', name: '灵视药剂', path: '/alchemy/PotionVision', url: '/images/alchemy/part-Slice236.png' },
            { type: '6', index: '28', name: '麻痹药剂', path: '/alchemy/PotionParalyse', url: '/images/alchemy/part-Slice236.png' },
            { type: '6', index: '29', name: '净化药剂', path: '/alchemy/PotionPurify', url: '/images/alchemy/part-Slice233.png' },
            { type: '6', index: '30', name: '力量药剂', path: '/alchemy/PotionStr', url: '/images/alchemy/part-Slice233.png' },
            { type: '6', index: '31', name: '毒气药剂', path: '/alchemy/PotionGas', url: '/images/alchemy/part-Slice233.png' },
            { type: '6', index: '32', name: '鉴定卷轴', path: '/alchemy/ScrollIdentify', url: '/images/alchemy/part-Slice200.png' },
            { type: '6', index: '33', name: '催眠卷轴', path: '/alchemy/ScrollSleep', url: '/images/alchemy/part-Slice200.png' },
            { type: '6', index: '34', name: '镜像卷轴', path: '/alchemy/ScrollImage', url: '/images/alchemy/part-Slice200.png' },
            { type: '6', index: '35', name: '探地卷轴', path: '/alchemy/ScrollMapping', url: '/images/alchemy/part-Slice202.png' },
            { type: '6', index: '36', name: '盛怒卷轴', path: '/alchemy/ScrollChallenge', url: '/images/alchemy/part-Slice202.png' },
            { type: '6', index: '37', name: '祛邪卷轴', path: '/alchemy/ScrollUncurse', url: '/images/alchemy/part-Slice202.png' },
            { type: '6', index: '38', name: '充能卷轴', path: '/alchemy/ScrollRecharging', url: '/images/alchemy/part-Slice196.png' },
            { type: '6', index: '39', name: '复仇卷轴', path: '/alchemy/ScrollRetribution', url: '/images/alchemy/part-Slice196.png' },
            { type: '6', index: '40', name: '恐惧卷轴', path: '/alchemy/ScrollTerror', url: '/images/alchemy/part-Slice196.png' },
            { type: '6', index: '41', name: '传送卷轴', path: '/alchemy/ScrollTp', url: '/images/alchemy/part-Slice206.png' },
            { type: '6', index: '42', name: '嬗变卷轴', path: '/alchemy/ScrollAlter', url: '/images/alchemy/part-Slice206.png' },
            { type: '6', index: '43', name: '升级卷轴', path: '/alchemy/ScrollUpgrade', url: '/images/alchemy/part-Slice206.png' },
            { type: '6', index: '44', name: '魔药', path: '/alchemy/PotionBrews', url: '/images/alchemy/part-Slice270.png' },
            { type: '6', index: '45', name: '秘药', path: '/alchemy/PotionElixirs', url: '/images/alchemy/part-Slice277.png' },
            { type: '6', index: '46', name: '结晶法术', path: '/alchemy/SpellSpells', url: '/images/alchemy/part-Slice285.png' },
            { type: '6', index: '47', name: '强化道具', path: '/alchemy/EnforcersDetails', url: '/images/alchemy/part-Slice257.png' },

            //炼金类
            { type: '7', index: '1', name: '魔能触媒', path: '/accessories/TrinketTrintetcatalyst', url: '/images/accessories/part-Slice54.png' },
            { type: '7', index: '2', name: '位面日暑', path: '/accessories/TrinketDimensionalsundial', url: '/images/accessories/part-Slice190.png' },
            { type: '7', index: '3', name: '奇异能晶', path: '/accessories/TrinketExoticcrystals', url: '/images/accessories/part-Slice188.png' },
            { type: '7', index: '4', name: '蝾螈灵眼', path: '/accessories/TrinketEyeofnewt', url: '/images/accessories/part-Slice195.png' },
            { type: '7', index: '5', name: '拟箱利齿', path: '/accessories/TrinketMimictooth', url: '/images/accessories/part-Slice193.png' },
            { type: '7', index: '6', name: '苔藓丛簇', path: '/accessories/TrinketMossyclump', url: '/images/accessories/part-Slice189.png' },
            { type: '7', index: '7', name: '残魔余卷', path: '/accessories/TrinketParchmentscrap', url: '/images/accessories/part-Slice186.png' },
            { type: '7', index: '8', name: '石化种子', path: '/accessories/TrinketPetrifiedseed', url: '/images/accessories/part-Slice187.png' },
            { type: '7', index: '9', name: '巨鼠头骨', path: '/accessories/TrinketSkull', url: '/images/accessories/part-Slice185.png' },
            { type: '7', index: '10', name: '十三叶草', path: '/accessories/TrinketClover', url: '/images/accessories/part-Slice191.png' },
            { type: '7', index: '11', name: '陷阱元件', path: '/accessories/TrinketTrapmechanism', url: '/images/accessories/part-Slice192.png' },
            { type: '7', index: '12', name: '奇迹聚酯', path: '/accessories/TrinketWondrousresin', url: '/images/accessories/part-Slice194.png' },
            { type: '7', index: '13', name: '血饮魔瓶', path: '/accessories/Trinketvialofblood', url: '/images/accessories/vialofblood.png' },
            { type: '7', index: '14', name: '遗忘碎片', path: '/accessories/Trinketshardofoblivion', url: '/images/accessories/shardofoblivion.png' },
            { type: '7', index: '15', name: '混乱香炉', path: '/accessories/Trinketchaoticcenser', url: '/images/accessories/chaoticcenser.png' },
            

            //怪物和NPC类
            { type: '8', index: '1', name: '第一区域', path: '/monsterornpc/Ch1View', url: '/images/monsterornpc/tiles_sewers/part-Slice1.png' },
            { type: '8', index: '2', name: '啮齿小鼠', path: '/monsterornpc/Ch1Rat', url: '/images/monsterornpc/rat/part-Slice1.png' },
            { type: '8', index: '3', name: '白化老鼠', path: '/monsterornpc/Ch1Albino', url: '/images/monsterornpc/rat/part-Slice16.png' },
            { type: '8', index: '4', name: '下水道巨蛇', path: '/monsterornpc/Ch1Snake', url: '/images/monsterornpc/snake/part-Slice1.png' },
            { type: '8', index: '5', name: '豺狼巡查', path: '/monsterornpc/Ch1Gnoll', url: '/images/monsterornpc/gnoll/part-Slice1.png' },
            { type: '8', index: '6', name: '腐臭老鼠', path: '/monsterornpc/Ch1Frat', url: '/images/monsterornpc/rat/part-Slice31.png' },
            { type: '8', index: '7', name: '下水道螃蟹', path: '/monsterornpc/Ch1Crab', url: '/images/monsterornpc/crab/part-Slice1.png' },
            { type: '8', index: '8', name: '豺狼诡术师', path: '/monsterornpc/Ch1Gnolldarter', url: '/images/monsterornpc/gnoll/part-Slice12.png' },
            { type: '8', index: '9', name: '蝇群', path: '/monsterornpc/Ch1Swarm', url: '/images/monsterornpc/swarm/part-Slice1.png' },
            { type: '8', index: '10', name: '史莱姆', path: '/monsterornpc/Ch1Slime', url: '/images/monsterornpc/slime/part-Slice2.png' },
            { type: '8', index: '11', name: '蚀化史莱姆', path: '/monsterornpc/Ch1Causticslime', url: '/images/monsterornpc/slime/part-Slice10.png' },
            { type: '8', index: '12', name: '巨大螃蟹', path: '/monsterornpc/Ch1Greatcrab', url: '/images/monsterornpc/crab/part-Slice15.png' },
            { type: '8', index: '13', name: '第一区域boss', path: '/monsterornpc/Ch1Div', url: '/images/monsterornpc/goo/part-Slice7.png' },
            { type: '8', index: '14', name: '粘咕', path: '/monsterornpc/Ch1Goo', url: '/images/monsterornpc/goo/part-Slice4.png' },
            { type: '8', index: '15', name: '第二区域', path: '/monsterornpc/Ch2View', url: '/images/monsterornpc/tiles_prison/part-Slice1.png' },
            { type: '8', index: '16', name: '疯狂小偷', path: '/monsterornpc/Ch2Thief', url: '/images/monsterornpc/thief/part-Slice1.png' },
            { type: '8', index: '17', name: '疯狂强盗', path: '/monsterornpc/Ch2Bandit', url: '/images/monsterornpc/thief/part-Slice14.png' },
            { type: '8', index: '18', name: '骷髅', path: '/monsterornpc/Ch2Skeleton', url: '/images/monsterornpc/skeleton/part-Slice1.png' },
            { type: '8', index: '19', name: 'DM-100', path: '/monsterornpc/Ch2Dm100', url: '/images/monsterornpc/dm100/part-Slice1.png' },
            { type: '8', index: '20', name: '监狱守卫', path: '/monsterornpc/Ch2Guard', url: '/images/monsterornpc/guard/part-Slice1.png' },
            { type: '8', index: '21', name: '死灵法师', path: '/monsterornpc/Ch2Necro', url: '/images/monsterornpc/necromancer/part-Slice1.png' },
            { type: '8', index: '22', name: '招魂法师', path: '/monsterornpc/Ch2Spenecro', url: '/images/monsterornpc/necromancer/part-Slice14.png' },
            { type: '8', index: '23', name: '腐烂之心', path: '/monsterornpc/Ch2Rotheart', url: '/images/monsterornpc/rot_heart/part-Slice1.png' },
            { type: '8', index: '24', name: '腐烂触手', path: '/monsterornpc/Ch2Rotlash', url: '/images/monsterornpc/rot_lasher/part-Slice1.png' },
            { type: '8', index: '25', name: '新生火元素', path: '/monsterornpc/Ch2Newelefire', url: '/images/monsterornpc/elemental/part-Slice15.png' },
            { type: '8', index: '26', name: '第二区域boss', path: '/monsterornpc/Ch2Div', url: '/images/monsterornpc/tengu/part-Slice6.png' },
            { type: '8', index: '27', name: '天狗', path: '/monsterornpc/Ch2Tengu', url: '/images/monsterornpc/tengu/part-Slice1.png' },
            { type: '8', index: '30', name: '第三区域', path: '/monsterornpc/Ch3View', url: '/images/monsterornpc/tiles_caves/part-Slice1.png' },
            { type: '8', index: '31', name: '吸血蝙蝠', path: '/monsterornpc/Ch3Bat', url: '/images/monsterornpc/bat/part-Slice1.png' },
            { type: '8', index: '32', name: '豺狼暴徒', path: '/monsterornpc/Ch3Brute', url: '/images/monsterornpc/brute/part-Slice1.png' },
            { type: '8', index: '33', name: '重甲暴徒', path: '/monsterornpc/Ch3Armoredbrute', url: '/images/monsterornpc/brute/part-Slice12.png' },
            { type: '8', index: '34', name: '豺狼萨满', path: '/monsterornpc/Ch3Shaman', url: '/images/monsterornpc/shaman/part-Slice1.png' },
            { type: '8', index: '35', name: '矿洞蜘蛛', path: '/monsterornpc/Ch3Spinner', url: '/images/monsterornpc/spinner/part-Slice1.png' },
            { type: '8', index: '36', name: 'DM-200', path: '/monsterornpc/Ch3Dm200', url: '/images/monsterornpc/dm200/part-Slice1.png' },
            { type: '8', index: '37', name: 'DM-201', path: '/monsterornpc/Ch3Dm201', url: '/images/monsterornpc/dm200/part-Slice13.png' },
            { type: '8', index: '38', name: '第三区域boss', path: '/monsterornpc/Ch3Div', url: '/images/monsterornpc/dm300/part-Slice9.png' },
            { type: '8', index: '39', name: '能源塔', path: '/monsterornpc/Ch3Pylon', url: '/images/monsterornpc/pylon/part-Slice1.png' },
            { type: '8', index: '40', name: 'DM-300', path: '/monsterornpc/Ch3Dm300', url: '/images/monsterornpc/dm300/part-Slice1.png' },
            { type: '8', index: '41', name: '第四区域', path: '/monsterornpc/Ch4View', url: '/images/monsterornpc/tiles_city/part-Slice1.png' },
            { type: '8', index: '42', name: '矮人尸群', path: '/monsterornpc/Ch4Ghoul', url: '/images/monsterornpc/ghoul/part-Slice1.png' },
            { type: '8', index: '43', name: '矮人术士', path: '/monsterornpc/Ch4Warlock', url: '/images/monsterornpc/warlock/part-Slice1.png' },
            { type: '8', index: '44', name: '火元素', path: '/monsterornpc/Ch4Elefire', url: '/images/monsterornpc/elemental/part-Slice1.png' },
            { type: '8', index: '45', name: '冰霜元素', path: '/monsterornpc/Ch4Elefrost', url: '/images/monsterornpc/elemental/part-Slice29.png' },
            { type: '8', index: '46', name: '电击元素', path: '/monsterornpc/Ch4Eleshock', url: '/images/monsterornpc/elemental/part-Slice43.png' },
            { type: '8', index: '47', name: '混沌元素', path: '/monsterornpc/Ch4Elechaos', url: '/images/monsterornpc/elemental/part-Slice57.png' },
            { type: '8', index: '48', name: '矮人武僧', path: '/monsterornpc/Ch4Monk', url: '/images/monsterornpc/monk/part-Slice1.png' },
            { type: '8', index: '49', name: '武僧大师', path: '/monsterornpc/Ch4Senior', url: '/images/monsterornpc/monk/part-Slice18.png' },
            { type: '8', index: '50', name: '魔像', path: '/monsterornpc/Ch4Golem', url: '/images/monsterornpc/golem/part-Slice1.png' },
            { type: '8', index: '51', name: '第四区域boss', path: '/monsterornpc/Ch4Div', url: '/images/monsterornpc/king/part-Slice16.png' },
            { type: '8', index: '52', name: '矮人国王', path: '/monsterornpc/Ch4King', url: '/images/monsterornpc/king/part-Slice1.png' },
            { type: '8', index: '53', name: '第五区域', path: '/monsterornpc/Ch5View', url: '/images/monsterornpc/tiles_halls/part-Slice1.png' },
            { type: '8', index: '54', name: '恶魔血巢', path: '/monsterornpc/Ch5Spawner', url: '/images/monsterornpc/spawner/part-Slice1.png' },
            { type: '8', index: '55', name: '恶魔撕裂者', path: '/monsterornpc/Ch5Ripper', url: '/images/monsterornpc/ripper/part-Slice1.png' },
            { type: '8', index: '56', name: '魅魔', path: '/monsterornpc/Ch5Succubus', url: '/images/monsterornpc/succubus/part-Slice1.png' },
            { type: '8', index: '57', name: '邪恶之眼', path: '/monsterornpc/Ch5Eye', url: '/images/monsterornpc/eye/part-Slice1.png' },
            { type: '8', index: '58', name: '巨型蝎子', path: '/monsterornpc/Ch5Scorpio', url: '/images/monsterornpc/scorpio/part-Slice1.png' },
            { type: '8', index: '59', name: '酸液蝎子', path: '/monsterornpc/Ch5Acidic', url: '/images/monsterornpc/scorpio/part-Slice12.png' },
            { type: '8', index: '60', name: '第五区域boss', path: '/monsterornpc/Ch5Div', url: '/images/monsterornpc/yog/part-Slice10.png' },
            { type: '8', index: '61', name: '燃烧之拳&大地之拳', path: '/monsterornpc/Ch5Fist1', url: '/images/monsterornpc/yog_fists/part-Slice1.png' },
            { type: '8', index: '62', name: '腐烂之拳&锈蚀之拳', path: '/monsterornpc/Ch5Fist2', url: '/images/monsterornpc/yog_fists/part-Slice15.png' },
            { type: '8', index: '63', name: '辉耀之拳&暗影之拳', path: '/monsterornpc/Ch5Fist3', url: '/images/monsterornpc/yog_fists/part-Slice29.png' },
            { type: '8', index: '64', name: '古神幼虫', path: '/monsterornpc/Ch5Larva', url: '/images/monsterornpc/larva/part-Slice1.png' },
            { type: '8', index: '65', name: 'Yog-Dzewa', path: '/monsterornpc/Ch5Yog', url: '/images/monsterornpc/yog/part-Slice1.png' },
            { type: '8', index: '66', name: '广谱怪物与NPC', path: '/monsterornpc/NeutralView', url: '/images/monsterornpc/mimic/part-Slice42.png' },
            { type: '8', index: '67', name: '活化石像', path: '/monsterornpc/StatueView', url: '/images/monsterornpc/statue/part-Slice1.png' },
            { type: '8', index: '68', name: '装甲石像', path: '/monsterornpc/ArmoredStatue', url: '/images/monsterornpc/statue/part-Slice62.png' },
            { type: '8', index: '69', name: '巨型食人鱼', path: '/monsterornpc/FishView', url: '/images/monsterornpc/piranha/part-Slice1.png' },
            { type: '8', index: '70', name: '宝箱怪', path: '/monsterornpc/MimicView', url: '/images/monsterornpc/mimic/part-Slice3.png' },
            { type: '8', index: '71', name: '金色宝箱怪', path: '/monsterornpc/MimicGolden', url: '/images/monsterornpc/mimic/part-Slice16.png' },
            { type: '8', index: '72', name: '水晶宝箱怪', path: '/monsterornpc/MimicCrystal', url: '/images/monsterornpc/mimic/part-Slice29.png' },
            { type: '8', index: '73', name: '怨灵', path: '/monsterornpc/WraithView', url: '/images/monsterornpc/wraith/part-Slice1.png' },
            { type: '8', index: '74', name: '金色蜜蜂', path: '/monsterornpc/BeeView', url: '/images/monsterornpc/bee/part-Slice1.png' },
            { type: '8', index: '75', name: '咒缚灵', path: '/monsterornpc/TormentedSpirit', url: '/images/monsterornpc/wraith/part-Slice9.png' },
            { type: '8', index: '76', name: '幻影食人鱼', path: '/monsterornpc/PhantomPiranha', url: '/images/monsterornpc/piranha/part-Slice16.png' },
            { type: '8', index: '77', name: '悲伤幽灵', path: '/monsterornpc/GhostView', url: '/images/monsterornpc/ghost/part-Slice1.png' },
            { type: '8', index: '78', name: '老杖匠', path: '/monsterornpc/WandMaker', url: '/images/monsterornpc/wandmaker/part-Slice1.png' },
            { type: '8', index: '79', name: '巨魔铁匠', path: '/monsterornpc/BlackSmith', url: '/images/monsterornpc/blacksmith/part-Slice1.png' },
            { type: '8', index: '80', name: '野心勃勃的小恶魔', path: '/monsterornpc/ImpView', url: '/images/monsterornpc/demon/part-Slice1.png' },
            { type: '8', index: '81', name: '镜像', path: '/monsterornpc/ImageView', url: '/images/monsterornpc/warrior/part-Slice2.png' },
            { type: '8', index: '82', name: '虹色幻影', path: '/monsterornpc/PrisImage', url: '/images/monsterornpc/warrior/part-Slice1.png' },
            { type: '8', index: '83', name: '鼠王', path: '/monsterornpc/RatKing', url: '/images/monsterornpc/ratking/part-Slice8.png' },
            { type: '8', index: '84', name: '魔法绵羊', path: '/monsterornpc/SheepView', url: '/images/monsterornpc/sheep/part-Slice1.png' },
            { type: '8', index: '85', name: '血色哨卫', path: '/monsterornpc/RedSentry', url: '/images/monsterornpc/red_sentry/part-Slice1.png' },
            { type: '8', index: '86', name: '水晶尖塔', path: '/monsterornpc/CrystalSpire', url: '/images/monsterornpc/crystal_spire/part-Slice1.png' },
            { type: '8', index: '87', name: '水晶哨兵', path: '/monsterornpc/CrystalGuardian', url: '/images/monsterornpc/crystal_guardian/part-Slice1.png' },
            { type: '8', index: '88', name: '灵性晶簇', path: '/monsterornpc/CrystalWisp', url: '/images/monsterornpc/crystal_wisp/part-Slice1.png' },
            { type: '8', index: '89', name: '豺狼地卜师', path: '/monsterornpc/GnollGeomancer', url: '/images/monsterornpc/gnoll_geomancer/part-Slice1.png' },
            { type: '8', index: '90', name: '豺狼守卫', path: '/monsterornpc/GnollGuard', url: '/images/monsterornpc/gnoll_guard/part-Slice1.png' },
            { type: '8', index: '91', name: '豺狼矿工', path: '/monsterornpc/GnollSapper', url: '/images/monsterornpc/gnoll_sapper/part-Slice1.png' },

            //杂项1
            { type: '9', index: '1', name: '负面效果', path: '/miscellaneous1/BuffNeg1', url: '/images/miscellaneous/large_buffs/part-Slice15.png' },
            { type: '9', index: '2', name: '正面效果', path: '/miscellaneous1/BuffPos1', url: '/images/miscellaneous/large_buffs/part-Slice20.png' },
            { type: '9', index: '3', name: '陷阱', path: '/miscellaneous1/Trap1View', url: '/images/miscellaneous/terrain_features/part-Slice64.png' },
            { type: '9', index: '4', name: '护符诡咒', path: '/miscellaneous1/AmuletCurse', url: '/images/miscellaneous/large_buffs/part-Slice60.png' },
            { type: '9', index: '5', name: '献祭之火', path: '/miscellaneous1/SacFire', url: '/images/miscellaneous/large_buffs/part-Slice40.png' },
            { type: '9', index: '6', name: '重生十字架', path: '/miscellaneous1/AnkhView', url: '/images/miscellaneous/part-Slice33.png' },
            { type: '9', index: '7', name: '破损纹章', path: '/miscellaneous1/SealView', url: '/images/miscellaneous/part-Slice35.png' },
            { type: '9', index: '8', name: '金币', path: '/miscellaneous1/GoldView', url: '/images/miscellaneous/part-Slice16.png' },
            { type: '9', index: '9', name: '尸尘', path: '/miscellaneous1/DustView', url: '/images/miscellaneous/part-Slice318.png' },
            { type: '9', index: '10', name: '暗金矿', path: '/miscellaneous1/OreView', url: '/images/miscellaneous/part-Slice322.png' },

            //杂项2
            { type: '10', index: '1', name: '版本介绍', path: '/miscellaneous2/IntroView', url: '/images/monsterornpc/mimic/part-Slice48.png' },
            { type: '10', index: '2', name: '武器与护甲等阶', path: '/miscellaneous2/TierView', url: '/images/weapons/part-Slice93.png' },
            { type: '10', index: '3', name: '武器', path: '/miscellaneous2/MeleeView', url: '/images/miscellaneous/melee.gif' },
            { type: '10', index: '4', name: '投掷武器', path: '/miscellaneous2/RangedView', url: '/images/miscellaneous/ranged.gif' },
            { type: '10', index: '5', name: '护甲', path: '/miscellaneous2/ArmorView', url: '/images/miscellaneous/armor.gif' },
            { type: '10', index: '6', name: '法杖', path: '/miscellaneous2/WandView', url: '/images/miscellaneous/wand.gif' },
            { type: '10', index: '7', name: '诅咒法杖', path: '/miscellaneous2/WandCursed', url: '/images/weapons/part-Slice288.png' },
            { type: '10', index: '8', name: '戒指', path: '/miscellaneous2/RingView', url: '/images/miscellaneous/ring.gif' },
            { type: '10', index: '9', name: '神器', path: '/miscellaneous2/ArtifactView', url: '/images/miscellaneous/artifact.gif' },
            { type: '10', index: '10', name: '卷轴', path: '/miscellaneous2/ScrollView', url: '/images/miscellaneous/scroll.gif' },
            { type: '10', index: '11', name: '药水', path: '/miscellaneous2/PotionView', url: '/images/miscellaneous/potion.gif' },
            { type: '10', index: '12', name: '治疗药水限制掉落', path: '/miscellaneous2/LimDrop', url: '/images/alchemy/part-Slice233.png' },
            { type: '10', index: '13', name: '食物', path: '/miscellaneous2/FoodView', url: '/images/miscellaneous/food.gif' },
            { type: '10', index: '14', name: '角色优先级', path: '/miscellaneous2/PriorityView', url: '/images/artifact/part-Slice166.png' },
            { type: '10', index: '15', name: '英雄', path: '/miscellaneous2/HeroView', url: '/images/miscellaneous/hero.gif' },
            { type: '10', index: '16', name: '怪物', path: '/miscellaneous2/MobView', url: '/images/miscellaneous/mob.gif' },
            { type: '10', index: '17', name: '怪物属性', path: '/miscellaneous2/PropertyView', url: '/images/miscellaneous/property.gif' },
            { type: '10', index: '18', name: '怪物生成', path: '/miscellaneous2/SpawnView', url: '/images/miscellaneous/spawn.gif' },
            { type: '10', index: '19', name: '商店', path: '/miscellaneous2/ShopView', url: '/images/miscellaneous/part-Slice16.png' },
            { type: '10', index: '20', name: '感觉', path: '/miscellaneous2/FeelingView', url: '/images/miscellaneous/feeling.png' },
            { type: '10', index: '21', name: '裂缝', path: '/miscellaneous2/ChasmView', url: '/images/alchemy/part-Slice287.png' },
            { type: '10', index: '22', name: '楼层封锁', path: '/miscellaneous2/LckFloor', url: '/images/miscellaneous/large_buffs/part-Slice36.png' },
            { type: '10', index: '23', name: '排行榜', path: '/miscellaneous2/RankingView', url: '/images/miscellaneous/ranking.png' },
            { type: '10', index: '24', name: '英雄遗骸', path: '/miscellaneous2/BonesView', url: '/images/miscellaneous/bones.png' },
            { type: '10', index: '25', name: '战斗机制', path: '/miscellaneous2/MechView', url: '/images/weapons/part-Slice70.png' },
            { type: '10', index: '26', name: '铁匠任务', path: '/miscellaneous2/BlackSmith', url: '/images/miscellaneous/blacksmith.gif' },
            { type: '10', index: '27', name: '铁匠任务补充', path: '/miscellaneous2/BlackSmith1', url: '/images/monsterornpc/blacksmith/part-Slice1.png' },

        ]
    }),
    actions: {
        setActiveTopMenu(type) {
            this.activeTopMenu = type;
            localStorage.setItem('activeTopMenu', type);
        },
        setActiveSidebarMenu(index) {
            this.activeSidebarMenu = index;
            localStorage.setItem('activeSidebarMenu', index);
        }
    },
    getters: {
        getMenuItemsByType: (state) => (type) => {
            return state.menuItems.filter(item => item.type === type);
        }
    }
});
